<a href="https://colab.research.google.com/github/LorenzoDonatti/TCC_DeepLearning_VLC/blob/main/OOK_SVM_TCC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ALGORITMOS DE DEEP LEARNING EM DATASETS DE COMUNICAÇÃO POR LUZ VISIVEL**

---


TRABALHO DE CONCLUSÃO DE CURSO DO ALUNO LORENZO MOREIRA DONATTI.

# Funções que baixam arquivos Paralelamente

---



Caso nao seja possível utilizar a biblioteca Gdown na pasta especificada, este metodo de download deve ser utilizado.

In [ ]:
'''import requests
from multiprocessing import cpu_count
from multiprocessing.pool import ThreadPool

def download_paralel(args):
  cpus = cpu_count()
  results = ThreadPool(cpus - 1).imap_unordered(download_url, args)


def download_url(args):
  url, output = args[0], args[1]  
  try:
    gdown.download(url, output, quiet=False, fuzzy=True)
  except Exception as e:
    print("Problem downloading", e) ''' 


'import requests\nfrom multiprocessing import cpu_count\nfrom multiprocessing.pool import ThreadPool\n\ndef download_paralel(args):\n  cpus = cpu_count()\n  results = ThreadPool(cpus - 1).imap_unordered(download_url, args)\n\n\ndef download_url(args):\n  url, output = args[0], args[1]  \n  try:\n    gdown.download(url, output, quiet=False, fuzzy=True)\n  except Exception as e:\n    print("Problem downloading", e) '

In [ ]:
############ EXEMPLO DE CELULA PARA QUANDO O GDOWN NAO CONSEGUIR ACESSO AO FOLDER####################
############ PROCESSO MANUAL ########################

'''from scipy.io import loadmat
import numpy as np
import pandas as pd
import gdown

urls = ["https://drive.google.com/file/d/1dr6tI_XffRVehcLZByUX1JG476C4Lp7G/view?usp=sharing", 
        "https://drive.google.com/file/d/1klSvkJVIViRFhDbxATzmu0Q1DALoWbJ4/view?usp=sharing",
        "https://drive.google.com/file/d/1IaVRZB8PtGCjSBZNgEoV-vFtqfndNdX2/view?usp=sharing",
        "https://drive.google.com/file/d/1XeMiywqTwJvyCFNYt3d5mdBNJmYoqZgt/view?usp=sharing",
        "https://drive.google.com/file/d/1DGKYFy5Ae0rqLqBozXUDY7EuIY0cbQdP/view?usp=sharing",
        "https://drive.google.com/file/d/1vPhsrgRWkv1V21lfyfx1BjIw8u4gj3XL/view?usp=sharing",
        "https://drive.google.com/file/d/1KQn4ljEl-6RRIDtv8a0muO8XvylmtYgh/view?usp=sharing",
        "https://drive.google.com/file/d/16KNK14QYCJTLHy0ytHlUJfXgZYfEodQ6/view?usp=sharing",
        "https://drive.google.com/file/d/1hQXpC6StuXM4gJDBiWi-ciIr2IMg00fz/view?usp=sharing",
        "https://drive.google.com/file/d/1aOvbkHgneQgWCP8ee95cuL834TU2u9lO/view?usp=sharing",
        "https://drive.google.com/file/d/1XHKMqqJqw4gVSKCB-4XXSo90z-C3qszE/view?usp=sharing",
        "https://drive.google.com/file/d/1pcJh6eRnifmh6F5HxSPZGIX_Z9n-B6bz/view?usp=sharing",
        "https://drive.google.com/file/d/1k6W4NTXfZvXEVQkZQmcITILCpYiHzB8a/view?usp=sharing",
        "https://drive.google.com/file/d/1TCWdZ22pKpy73F-mp2ZrsPnSqdYSvSEa/view?usp=sharing",
        "https://drive.google.com/file/d/1Wy015sMCoJJS1b8LsvIeiOLlQsrGzalD/view?usp=sharing",
        "https://drive.google.com/file/d/1KU10g1qWy8ZG3QcJJ6Yv0ubzlZQFuYeP/view?usp=sharing",
        "https://drive.google.com/file/d/1nYBUSSelA_L0LyIhTty8GcIkT2mYnw51/view?usp=sharing",
        "https://drive.google.com/file/d/1O99b7y3nzcv5je17DTjVRfPWKKfRm7Tb/view?usp=sharing"]

outputs= ["0cm.mat", "10cm.mat", "20cm.mat", "30cm.mat", "40cm.mat", "50cm.mat", "60cm.mat", "70cm.mat", "80cm.mat", "90cm.mat", "100cm.mat", 
          "110cm.mat", "120cm.mat", "130cm.mat", "140cm.mat", "150cm.mat", "160cm.mat", "170cm.mat", "180cm.mat", "label.mat"]       

inputs = zip(urls, outputs)

download_paralel(inputs)  '''


'from scipy.io import loadmat\nimport numpy as np\nimport pandas as pd\nimport gdown\n\nurls = ["https://drive.google.com/file/d/1dr6tI_XffRVehcLZByUX1JG476C4Lp7G/view?usp=sharing", \n        "https://drive.google.com/file/d/1klSvkJVIViRFhDbxATzmu0Q1DALoWbJ4/view?usp=sharing",\n        "https://drive.google.com/file/d/1IaVRZB8PtGCjSBZNgEoV-vFtqfndNdX2/view?usp=sharing",\n        "https://drive.google.com/file/d/1XeMiywqTwJvyCFNYt3d5mdBNJmYoqZgt/view?usp=sharing",\n        "https://drive.google.com/file/d/1DGKYFy5Ae0rqLqBozXUDY7EuIY0cbQdP/view?usp=sharing",\n        "https://drive.google.com/file/d/1vPhsrgRWkv1V21lfyfx1BjIw8u4gj3XL/view?usp=sharing",\n        "https://drive.google.com/file/d/1KQn4ljEl-6RRIDtv8a0muO8XvylmtYgh/view?usp=sharing",\n        "https://drive.google.com/file/d/16KNK14QYCJTLHy0ytHlUJfXgZYfEodQ6/view?usp=sharing",\n        "https://drive.google.com/file/d/1hQXpC6StuXM4gJDBiWi-ciIr2IMg00fz/view?usp=sharing",\n        "https://drive.google.com/file/d/1aOvbkHgneQgWCP

# Importação de Bibliotecas e Download da Pasta no Drive

---
Como o dataset foi baixado no GDrive, é possível baixar a pasta completa pela biblioteca gdown.
Ela ainda fornece como saída, os diretórios de todos arquivos baixados (guardar em variavel)


In [1]:
from scipy.io import loadmat
import numpy as np
import pandas as pd
import gdown

teste = "https://drive.google.com/drive/folders/1TkvBRg2PaKI1KFCpT_7xon6COiWL2ZqX?usp=sharing"
output = gdown.download_folder(teste, quiet=True, use_cookies=False,)

output

['/content/40/0cm.mat',
 '/content/40/5cm.mat',
 '/content/40/10cm.mat',
 '/content/40/15cm.mat',
 '/content/40/20cm.mat',
 '/content/40/25cm.mat',
 '/content/40/30cm.mat',
 '/content/40/35cm.mat',
 '/content/40/40cm.mat',
 '/content/40/45cm.mat',
 '/content/40/50cm.mat',
 '/content/40/55cm.mat',
 '/content/40/60cm.mat',
 '/content/40/65cm.mat',
 '/content/40/70cm.mat',
 '/content/40/75cm.mat',
 '/content/40/80cm.mat',
 '/content/40/85cm.mat',
 '/content/40/90cm.mat',
 '/content/40/95cm.mat',
 '/content/40/100cm.mat',
 '/content/40/105cm.mat',
 '/content/40/110cm.mat',
 '/content/40/115cm.mat',
 '/content/40/120cm.mat',
 '/content/40/125cm.mat',
 '/content/40/130cm.mat',
 '/content/40/135cm.mat',
 '/content/40/140cm.mat',
 '/content/40/145cm.mat',
 '/content/40/150cm.mat',
 '/content/40/155cm.mat',
 '/content/40/160cm.mat',
 '/content/40/165cm.mat',
 '/content/40/170cm.mat',
 '/content/40/175cm.mat',
 '/content/40/180cm.mat',
 '/content/40/label.mat']

# Abrindo arquivos .mat e identificando seu cabeçalho

---



Para a abertura de arquivos .mat foi necessário o módulo loadmat da biblioteca scipy.io. A função retorna um dicionário com diferentes Headers, onde apenas o ultimo será utilizado. 

Como todos arquivos da pasta serão abertos, o conteúdo de cada arquivo será guardado em uma posição de uma lista.

Os labels (saida y) estarão na ultima posição da lista 

In [2]:
########### ESSE PROCESSO É SUBSTITUIDO###########
exemplo = loadmat('/content/40/label.mat')
print(exemplo)

exemplo = exemplo['org_label']
print(exemplo)

########### POR ESSE PROCESSO ################
exemplo_otim = loadmat('/content/40/label.mat')
exemplo_otim = exemplo_otim[list(exemplo_otim.keys())[-1]]
print(exemplo_otim)

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN, Created on: Tue Jul 24 21:18:44 2018', '__version__': '1.0', '__globals__': [], 'org_label': array([[1, 0, 1, ..., 1, 1, 1]], dtype=uint8)}
[[1 0 1 ... 1 1 1]]
[[1 0 1 ... 1 1 1]]


In [3]:
datas = []

for o in output:
  data_test = loadmat(o)
  data_test = data_test[list(data_test.keys())[-1]]
  datas.append(data_test)

print(datas[-1], datas[0])

[[1 0 1 ... 1 1 1]] [[0.51724138 0.55172414 0.48275862 ... 0.51724138 0.55172414 0.55172414]
 [0.51724138 0.62068966 0.48275862 ... 0.5862069  0.55172414 0.5862069 ]
 [0.55172414 0.65517241 0.44827586 ... 0.65517241 0.62068966 0.65517241]
 ...
 [0.37931034 0.48275862 0.37931034 ... 0.37931034 0.31034483 0.34482759]
 [0.4137931  0.48275862 0.44827586 ... 0.37931034 0.37931034 0.4137931 ]
 [0.48275862 0.44827586 0.44827586 ... 0.48275862 0.44827586 0.44827586]]


# Preparação dos dados e Codificação dos valores Numéricos

---
É necessário codificar os dados em duas situações, quando forem categóricos (não numéricos) e quando estiverem com valores numéricos diferentes do escopo entre 0 e 1, a biblioteca sklearn fornece duas funções de fácil utilização e bem otimizadas.

Basicamente é feito um casting para int e após uma normalização dos dados.

Além disso, os dados do dataset vêm com o shape (1,x), e nosso modelo de machine learning somente aceitará vetores como parâmetro de saída, sendo necessário Transpor nossa estrutura.

Também, a função flatten é necessária para transformar a estrutura em um vetor de 1D.



In [4]:
print("Formatos originais dos dados: \n", datas[-1].shape, datas[0].shape, type(datas[-1]))

print("\nFormatos Transpostos dos dados: \n", datas[-1].T.shape, datas[0].T.shape)

print("\nUtilização do flatten: \n", datas[-1].flatten().shape)

print("\nDados sem flatten: \n", datas[-1].T, "\nDados com flatten: \n", datas[-1].flatten())

Formatos originais dos dados: 
 (1, 18000) (40, 18000) <class 'numpy.ndarray'>

Formatos Transpostos dos dados: 
 (18000, 1) (18000, 40)

Utilização do flatten: 
 (18000,)

Dados sem flatten: 
 [[1]
 [0]
 [1]
 ...
 [1]
 [1]
 [1]] 
Dados com flatten: 
 [1 0 1 ... 1 1 1]


In [5]:
from sklearn import preprocessing
from sklearn import utils

lab = preprocessing.LabelEncoder()
y_transf = lab.fit_transform(datas[-1].flatten())

print(y_transf)

[1 0 1 ... 1 1 1]


# Embaralhamento dos Dados

---

Começo da implementação de uma função que embaralha os dados em grupos simultaneamente, sem perder a ordem. Será implementado no futuro.

Talvez não seja necessário pois o dataset não possui "dados viciados", porém, é uma boa prática embaralhar dados.

In [ ]:
''' FUNÇÃO QUE EMBARALHA
def shuffle_list_matrix(lista, matriz):
  for i in range(len(lista)):
    j = np.random.randint(0,2)
    temp_list, temp_matriz = lista[i], matriz[i,:]
    lista[i], matriz[i,:] = lista[j], matriz[j,:]
    lista[j], matriz[j,:] = temp_list, temp_matriz

  return (lista, matriz)    
'''

''' NECESSARIO IMPLEMENTAR SHUFFLE MAIS ALEM
for i in range(len(data)):
  j = np.random.randint(0,len(data))
  templ, tempm = data[i], np.copy(data2[i,:])
  data[i], data2[i,:] = data[j], data2[j,:]
  data[j], data2[j,:] = templ, tempm

print(data)'''

' NECESSARIO IMPLEMENTAR SHUFFLE MAIS ALEM\nfor i in range(len(data)):\n  j = np.random.randint(0,len(data))\n  templ, tempm = data[i], np.copy(data2[i,:])\n  data[i], data2[i,:] = data[j], data2[j,:]\n  data[j], data2[j,:] = templ, tempm\n\nprint(data)'

# Modelo de Machine Learning (SVM)

---

As máquinas de vetores de suporte foram obtidas através da biblioteca scikitlearn, com o seguinte procedimento:

Como os valores que serão utilizados estão dentro de uma lista, foi necessário um laço de repetição, que percorrerá do inicio até o penultimo valor (ignorando o label, pois será a saída)

O primeiro passo é separar os dados de treino e os dados de teste, seria necessária a normalização, porém os dados do dataset já estão normalizados.

Os Parametros são

In [6]:
#Separação do conjunto de dados e testes e normalização
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

lab = preprocessing.LabelEncoder()
i=0
for data in datas[:-1]:
  X_train, X_test, y_train, y_test  = train_test_split(data.T, y_transf, test_size=0.33, random_state=0)

  ######################NORMALIZAÇÃO NAO É NECESSÁRIO POIS OS DADOS ESTAO NORMALIZADOS#################################
  #sc = MinMaxScaler()
  #X_train = sc.fit_transform(X_train)
  #X_test = sc.transform(X_test)
  #####################################################################################################################

  classifier = SVC(kernel = 'linear', decision_function_shape='ovo')
  classifier.fit(X_train, y_train)

  y_pred = classifier.predict(X_test)
  print("\nAcuracia:", accuracy_score(y_test, y_pred)*100, "%   Distancia:", i)
  i = i + 5


Acuracia: 100.0 %   Distancia: 0

Acuracia: 100.0 %   Distancia: 5

Acuracia: 100.0 %   Distancia: 10

Acuracia: 100.0 %   Distancia: 15

Acuracia: 100.0 %   Distancia: 20

Acuracia: 100.0 %   Distancia: 25

Acuracia: 100.0 %   Distancia: 30

Acuracia: 100.0 %   Distancia: 35

Acuracia: 100.0 %   Distancia: 40

Acuracia: 100.0 %   Distancia: 45

Acuracia: 100.0 %   Distancia: 50

Acuracia: 100.0 %   Distancia: 55

Acuracia: 100.0 %   Distancia: 60

Acuracia: 99.86531986531986 %   Distancia: 65

Acuracia: 99.73063973063972 %   Distancia: 70

Acuracia: 99.57912457912458 %   Distancia: 75

Acuracia: 99.04040404040404 %   Distancia: 80

Acuracia: 98.23232323232324 %   Distancia: 85

Acuracia: 97.76094276094275 %   Distancia: 90

Acuracia: 97.02020202020202 %   Distancia: 95

Acuracia: 96.06060606060606 %   Distancia: 100

Acuracia: 93.41750841750842 %   Distancia: 105

Acuracia: 91.78451178451178 %   Distancia: 110

Acuracia: 90.23569023569024 %   Distancia: 115

Acuracia: 88.400673400673

KeyboardInterrupt: ignored

# **ALGORITMO KNN**

---



In [66]:
from sklearn.neighbors import KNeighborsClassifier

i=0
for data in datas[:-1]:
  X_train, X_test, y_train, y_test  = train_test_split(data.T, y_transf, test_size=0.33, random_state=0)
  neigh = KNeighborsClassifier(n_neighbors=3)

  neigh.fit(X_train, y_train)

  y_pred = neigh.predict(X_test)

  print("\nAcuracia:", accuracy_score(y_test, y_pred)*100, "%   Distancia:", i)
  i = i + 5


Acuracia: 100.0 %   Distancia: 0

Acuracia: 100.0 %   Distancia: 5

Acuracia: 100.0 %   Distancia: 10

Acuracia: 100.0 %   Distancia: 15

Acuracia: 100.0 %   Distancia: 20

Acuracia: 100.0 %   Distancia: 25

Acuracia: 100.0 %   Distancia: 30

Acuracia: 100.0 %   Distancia: 35

Acuracia: 100.0 %   Distancia: 40

Acuracia: 100.0 %   Distancia: 45

Acuracia: 100.0 %   Distancia: 50

Acuracia: 100.0 %   Distancia: 55

Acuracia: 99.93265993265993 %   Distancia: 60

Acuracia: 99.86531986531986 %   Distancia: 65

Acuracia: 99.5959595959596 %   Distancia: 70

Acuracia: 98.73737373737373 %   Distancia: 75

Acuracia: 98.1144781144781 %   Distancia: 80

Acuracia: 96.86868686868686 %   Distancia: 85

Acuracia: 95.58922558922559 %   Distancia: 90

Acuracia: 93.72053872053871 %   Distancia: 95

Acuracia: 92.76094276094277 %   Distancia: 100

Acuracia: 88.2996632996633 %   Distancia: 105

Acuracia: 84.91582491582491 %   Distancia: 110

Acuracia: 82.5925925925926 %   Distancia: 115

Acuracia: 80.0168

# **METODOS DE ENSEMBLE**

---




> # **Classificadores por Votação**



---


> Agrupa diversos classificadores fracos e a partir da maioria das classificações prediz a mais votada.


> Chamado de Hard Voting


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

log_clf = LogisticRegression()
tree_clf = DecisionTreeClassifier()
svm_clf = SVC()
knn_clf = KNeighborsClassifier(n_neighbors=3)

i=0
for data in datas[:-1]:
  X_train, X_test, y_train, y_test  = train_test_split(data.T, y_transf, test_size=0.33, random_state=0)

  voting_clf = VotingClassifier(estimators = [('lr',log_clf), 
                                              ('dt', tree_clf), 
                                              ('svc', svm_clf),
                                              ('knn', knn_clf)],
                                voting='hard'
  )

  voting_clf.fit(X_train, y_train)

  y_pred = voting_clf.predict(X_test)

  print("\nAcuracia:", accuracy_score(y_test, y_pred)*100, "%   Distancia:", i)
  i = i + 5


Acuracia: 100.0 %   Distancia: 0

Acuracia: 100.0 %   Distancia: 5

Acuracia: 100.0 %   Distancia: 10

Acuracia: 100.0 %   Distancia: 15

Acuracia: 100.0 %   Distancia: 20

Acuracia: 100.0 %   Distancia: 25

Acuracia: 100.0 %   Distancia: 30

Acuracia: 100.0 %   Distancia: 35

Acuracia: 100.0 %   Distancia: 40

Acuracia: 100.0 %   Distancia: 45

Acuracia: 100.0 %   Distancia: 50

Acuracia: 100.0 %   Distancia: 55

Acuracia: 99.98316498316498 %   Distancia: 60

Acuracia: 99.86531986531986 %   Distancia: 65

Acuracia: 99.76430976430977 %   Distancia: 70

Acuracia: 99.41077441077442 %   Distancia: 75

Acuracia: 98.87205387205387 %   Distancia: 80

Acuracia: 98.13131313131314 %   Distancia: 85

Acuracia: 97.32323232323232 %   Distancia: 90

Acuracia: 96.34680134680134 %   Distancia: 95

Acuracia: 95.38720538720538 %   Distancia: 100

Acuracia: 92.77777777777779 %   Distancia: 105

Acuracia: 90.65656565656566 %   Distancia: 110

Acuracia: 89.02356902356902 %   Distancia: 115

Acuracia: 86.


 > # **Classificador por Bagging**

---


> Ao invés de agrupar diversos Classificadores diferentes, este metodo de ensemble utiliza apenas um tipo de classificador, criando subconjuntos aleatorios no conjunto de treinamento.


> Este tipo de ensemble se diferencia dos demais pois as predições podem ser feitas paralelamente. (Parâmetro n_jobs)

In [60]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KNeighborsClassifier

i=0
for data in datas[:-1]:
  X_train, X_test, y_train, y_test  = train_test_split(data.T, y_transf, test_size=0.33, random_state=0)
  bag_clf = BaggingClassifier(KNeighborsClassifier(), n_estimators = 500, max_samples=100, bootstrap=True)

  bag_clf.fit(X_train, y_train)

  y_pred = bag_clf.predict(X_test)

  print("\nAcuracia:", accuracy_score(y_test, y_pred)*100, "%   Distancia:", i)
  i = i + 5


Acuracia: 100.0 %   Distancia: 0

Acuracia: 100.0 %   Distancia: 5

Acuracia: 100.0 %   Distancia: 10

Acuracia: 100.0 %   Distancia: 15

Acuracia: 100.0 %   Distancia: 20

Acuracia: 100.0 %   Distancia: 25

Acuracia: 100.0 %   Distancia: 30

Acuracia: 100.0 %   Distancia: 35

Acuracia: 100.0 %   Distancia: 40

Acuracia: 100.0 %   Distancia: 45

Acuracia: 100.0 %   Distancia: 50

Acuracia: 100.0 %   Distancia: 55

Acuracia: 100.0 %   Distancia: 60

Acuracia: 99.84848484848486 %   Distancia: 65

Acuracia: 99.79797979797979 %   Distancia: 70

Acuracia: 99.54545454545455 %   Distancia: 75

Acuracia: 98.92255892255892 %   Distancia: 80

Acuracia: 98.31649831649831 %   Distancia: 85

Acuracia: 97.67676767676767 %   Distancia: 90

Acuracia: 96.76767676767678 %   Distancia: 95

Acuracia: 95.57239057239057 %   Distancia: 100

Acuracia: 93.14814814814815 %   Distancia: 105

Acuracia: 91.44781144781145 %   Distancia: 110

Acuracia: 90.21885521885523 %   Distancia: 115

Acuracia: 88.030303030303

KeyboardInterrupt: ignored


> # **Florestas Aleatórias**

---

> Quando o Bagging é utilizado em Decision Trees (Arvores de Decisão), um novo algoritmo chamado Random Forest é criado.



> A biblioteca Scikit Learn conta com um modulo dedicado apenas as Random Forests.




In [65]:
from sklearn.ensemble import RandomForestClassifier

i=0
for data in datas[:-1]:
  X_train, X_test, y_train, y_test  = train_test_split(data.T, y_transf, test_size=0.33, random_state=0)
  clf = RandomForestClassifier(max_depth=2, random_state=0)
  clf.fit(X_train, y_train)

  y_pred = clf.predict(X_test)

  print("\nAcuracia:", accuracy_score(y_test, y_pred)*100, "%   Distancia:", i)
  i = i + 5


Acuracia: 100.0 %   Distancia: 0

Acuracia: 100.0 %   Distancia: 5

Acuracia: 100.0 %   Distancia: 10

Acuracia: 100.0 %   Distancia: 15

Acuracia: 100.0 %   Distancia: 20

Acuracia: 100.0 %   Distancia: 25

Acuracia: 100.0 %   Distancia: 30

Acuracia: 100.0 %   Distancia: 35

Acuracia: 100.0 %   Distancia: 40

Acuracia: 100.0 %   Distancia: 45

Acuracia: 99.98316498316498 %   Distancia: 50

Acuracia: 99.74747474747475 %   Distancia: 55

Acuracia: 99.57912457912458 %   Distancia: 60

Acuracia: 99.12457912457913 %   Distancia: 65

Acuracia: 98.48484848484848 %   Distancia: 70

Acuracia: 97.55892255892256 %   Distancia: 75

Acuracia: 96.0942760942761 %   Distancia: 80

Acuracia: 94.54545454545455 %   Distancia: 85

Acuracia: 93.73737373737374 %   Distancia: 90

Acuracia: 92.12121212121212 %   Distancia: 95

Acuracia: 89.91582491582491 %   Distancia: 100

Acuracia: 86.0942760942761 %   Distancia: 105

Acuracia: 84.02356902356902 %   Distancia: 110

Acuracia: 81.61616161616162 %   Distanc

# **BOOSTING**

---

Metodos de Boosting são metodos de ensemble que combinam classificadores fracos sequencialmente. Cada classificador tem objetivo de corrigir os erros do predecessor.

Serão abordados o Adaboost e o Gradient Boost.


> # **AdaBoost**



In [63]:
from sklearn.ensemble import AdaBoostClassifier
i=0
for data in datas[:-1]:
  X_train, X_test, y_train, y_test  = train_test_split(data.T, y_transf, test_size=0.33, random_state=0)
  clf = AdaBoostClassifier(base_estimator = SVC(probability=True, kernel='linear'), n_estimators=10, random_state=0)
  clf.fit(X_train, y_train)

  y_pred = clf.predict(X_test)

  print("\nAcuracia:", accuracy_score(y_test, y_pred)*100, "%   Distancia:", i)
  i = i + 5


Acuracia: 100.0 %   Distancia: 0

Acuracia: 100.0 %   Distancia: 5

Acuracia: 100.0 %   Distancia: 10

Acuracia: 100.0 %   Distancia: 15

Acuracia: 100.0 %   Distancia: 20

Acuracia: 100.0 %   Distancia: 25

Acuracia: 100.0 %   Distancia: 30

Acuracia: 100.0 %   Distancia: 35


KeyboardInterrupt: ignored


> # **Gradient Boost**




In [64]:
from sklearn.ensemble import GradientBoostingClassifier

i=0
for data in datas[:-1]:
  X_train, X_test, y_train, y_test  = train_test_split(data.T, y_transf, test_size=0.33, random_state=0)
  clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,
                                   max_depth=1, random_state=0)

  clf.fit(X_train, y_train)

  y_pred = clf.predict(X_test)

  print("\nAcuracia:", accuracy_score(y_test, y_pred)*100, "%   Distancia:", i)
  i = i + 5


Acuracia: 100.0 %   Distancia: 0

Acuracia: 100.0 %   Distancia: 5

Acuracia: 100.0 %   Distancia: 10

Acuracia: 100.0 %   Distancia: 15

Acuracia: 100.0 %   Distancia: 20

Acuracia: 99.98316498316498 %   Distancia: 25

Acuracia: 100.0 %   Distancia: 30

Acuracia: 100.0 %   Distancia: 35

Acuracia: 100.0 %   Distancia: 40

Acuracia: 100.0 %   Distancia: 45

Acuracia: 100.0 %   Distancia: 50

Acuracia: 99.94949494949495 %   Distancia: 55

Acuracia: 99.8989898989899 %   Distancia: 60

Acuracia: 99.62962962962963 %   Distancia: 65

Acuracia: 99.56228956228956 %   Distancia: 70

Acuracia: 99.19191919191918 %   Distancia: 75

Acuracia: 98.1144781144781 %   Distancia: 80

Acuracia: 97.60942760942761 %   Distancia: 85

Acuracia: 97.57575757575758 %   Distancia: 90

Acuracia: 95.77441077441078 %   Distancia: 95

Acuracia: 94.68013468013467 %   Distancia: 100

Acuracia: 92.15488215488216 %   Distancia: 105

Acuracia: 90.26936026936026 %   Distancia: 110

Acuracia: 88.61952861952862 %   Distanc